# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78416c219d808a5049b728bd69a6a461ae1f5d8b6c29a40833c03a7818e577133d46acb17195c5a3a41e09b1c77d9fd1c6dfa757d5839cef2872594f9dffa3cf

test:
  secret_key_base: 95e51e2a5d29b6e3e53a12f23ee0502cd286e1fcfa9c80160135a2969f352915bc31ccf2a27b32896f960620a80e2555224866d0202d2f2f583c22c02359f581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
